options:
    jjb-install-source:
        type: string
        default: 'git://github.com/openstack-infra/jenkins-job-builder.git'
        description: |
            Git repository to install jenkins-job-builder from.  Alternatively,
            you may run the 'make sourcedeps' target of the Makefile to
            package required assets into the charm prior to deploying, for
            environments where network access is restricted.  Any bundled
            package will override a any git repository set in config.
    config-repo:
        type: string
        description: |
            Bzr repository url containing collection of yaml files containing
            jenkins-job-builder configs. This may also be packaged locally
            prior to deploying by running 'make configrepo' target of the
            Makefile to pull from a specified repository.  Again, any bundled
            assets will override any setting set here.  The contents of this
            repository (or anything packaged with the charm) will end up
            installed in/etc/jenkins-job-builder/job-configs/ on the service
            unit.
    config-repo-revision:
        type: string
        default: "trunk"
        description: |
            If bzr repo specified, which revision to use.  Defaults to
            trunk, and is updated on during every config-changed hook.
    schedule-updates:
        type: boolean
        default: false
        description: |
            If configured to run from trunk of a remote repository, you may
            optionally have the charm install a cronjob that will periodically
            pull trunk and update Jenkins.
    update-frequency:
        type: string
        default: ''
        description: |
            If schedule-updates is True, update-frequency sets the schedule on
            which the cronjob updates the branch and pushes changes to Jenkins.
