options:
    jjb-install-source:
        type: string
        default: 'git://github.com/openstack-infra/jenkins-job-builder.git'
        description: |
            Git repository to install jenkins-job-builder from.  Alternatively,
            you may run the 'make sourcedeps' target of the Makefile to
            package required assets into the charm prior to deploying, for
            environments where network access is restricted.  Any bundled
            package will override a any git repository set in config.
    config-repo:
        type: string
        description: |
            Bzr repository url containing collection of yaml files containing
            jenkins-job-builder configs. This may also be packaged locally
            prior to deploying by running 'make configrepo' target of the
            Makefile to pull from a specified repository.  Again, any bundled
            assets will override any setting set here.  The contents of this
            repository (or anything packaged with the charm) will end up
            installed in/etc/jenkins-job-builder/job-configs/ on the service
            unit.
    config-repo-revision:
        type: string
        default: "trunk"
        description: |
            If bzr repo specified, which revision to use.  Defaults to
            trunk, and is updated on during every config-changed hook.
    lp-login:
        type: string
        default: ''
        description: |
            Launchpad login name of user branching bzr repo (required for
            private branches).
    ssh-privkey:
        type: string
        description: |
            SSH private key for associated LP user.
    ssh-pubkey:
        type: string
        description: |
            SSH public key for associated LP user.
    schedule-updates:
        type: boolean
        default: false
        description: |
            If configured to run from trunk of a remote repository, you may
            optionally have the charm install a cronjob that will periodically
            pull trunk and update Jenkins.
    update-frequency:
        type: string
        default: ''
        description: |
            If schedule-updates is True, update-frequency sets the schedule on
            which the cronjob updates the branch and pushes changes to Jenkins.
    update-trigger:
        type: string
        default: ''
        description: Used to force config-changed hook runs.
    lp-credentials-file:
        type: string
        default: ''
        description: |
            Credentials for login into Launchpad to retrieve team membership.
    lp-schedule:
        type: string
        default: "*/15 * * * *"
        description: |
            Cron-formatted schedule for launchpad sync
    jenkins-admin-user:
        type: string
        default: ""
        description: |
            Admin username to be used for Jenkins scripts.
    jenkins-token:
        type: string
        default: ""
        description: |
            API token that belongs to admin username, to be 
            used for Jenkins scripts. To set that, admin
            username should login by SSO at least once, and 
            retrieve the token found in user/xxx/configure.
            Each time the API token is changed, it needs to 
            be updated in this config option for the charm
        
